### ISSUE TITLE
按照目前的官方文档。@each @while 好像都不支持。

### ISSUE THREAD

**Issue by jincdream** [fex-team/fis-parser-sass#26]
``` sass
$i : 5;
@while $i > 0{
  .cmt-start-#($i):{
    width: 20px * $i;
  }
  $i = $i+1;
}
```
这样会报错。`` invalid property name``

**Comment by xiangshouding** [comment]
sass 原始是 ruby 写的，后来有人用 cpp 写了个 libsass，要把这个东西弄到 node 里面用就需要做二进制编译，这样就无法更新即时，如果遇到这样的问题请核实相关版本是否一致。

我们会不间断升级相关组件，但由于上面说的原因无法做到即时。
