### ISSUE TITLE
使用fis-parser-sass 插件，@import 的文件中的inline 图片，会报错

### ISSUE THREAD

**Issue by andge** [fex-team/fis-parser-sass#28]
common目录
a.scss
.a{
background-image: url('/img/a.png?__inline');
}
project
b.scss
@import '../common/a.scss';

a.scss 中不能使用inline 。

**Comment by 2betop** [comment]
有没有编译期跨模块引用？

**Comment by andge** [comment]
用一个fis.config编译的

**Comment by 2betop** [comment]
报啥错？路径确定写对了？

**Comment by andge** [comment]
不用inline 就没有问题

**Comment by 2betop** [comment]
windows 下面跑了一把，也没问题啊。你什么系统？

![image](https://cloud.githubusercontent.com/assets/2698393/8325664/ea8b698c-1a8d-11e5-8292-975719ca029d.png)

**Comment by andge** [comment]
windows 的系统。
出bug 的流程是这样的。
b.scss 引用你上面的a.scss ，编译出来的inline 就不正常了

**Comment by 2betop** [comment]
新版本已修复
