### ISSUE TITLE
使用fis3，如果使用插件是不是必须fis开头的插件才可以使用吗？

### ISSUE THREAD

**Issue by EagleWolf** [fex-team/fis-parser-sass#34]
现在使用babel-plugin-antd插件，好报下面的错误

[ERROR] unable to load plugin [fis3-optimizer-babel-plugin-antd] or [fis-optimizer-babel-plugin-antd]

**Comment by EagleWolf** [comment]
在线等，@2betop，请教怎么解决？

**Comment by 2betop** [comment]
是的，看你要解决什么问题了，可以自己封装个 fis 的插件。

**Comment by EagleWolf** [comment]
好的，谢谢。
